name: Push To Main

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: updates

      - name: Merge
        run: |
          git config --global user.email "InEase28@gmail.com"
          git config --global user.name "Mux"

          # hide-content-when-unfocused
          rm -rf hide-content-when-unfocused
          mv updates/hide-content-when-unfocused .

          # Color-Folder -> color-folder
          rm -rf color-folder
          mv updates/Color-Folder color-folder

          # remove update
          rm -rf updates

          # commit
          git add .
          git commit -m "Update Plugins"

      - name: Push Updates
        run: |
          git push
